### ISSUE TITLE
Need a way to allow `service.mock` suffix

### ISSUE THREAD

**Issue by MatanYadaev** [takuya-nakayasu/eslint-plugin-angular-file-naming#2]
Currently when I enter `service.mock` suffix it doesn't catch. I have to enter just `mock` suffix which isn't accurate enough.

**Comment by takuya-nakayasu** [comment]
This issue has been resolved in v1.0.4.

**Comment by takuya-nakayasu** [comment]
@MatanYadaev 
Sorry for the late response.
This issue has been resolved in v1.0.4.
